serverFiles:
  prometheus:
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      - job_name: 'kubernetes-cadvisor'
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: cadvisor
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8080"
      - job_name: 'node-exporter'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "9100"

image:
  repository: prom/prometheus
  tag: v2.51.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090
  targetPort: 9090

ingress:
  enabled: true
  ingressClassName: traefik
  clusterIssuer: letsencrypt-http
  serviceName: prometheus
  hosts:
    - prometheus.byhyeon.com
  tls:
    - secretName: prometheus-tls
      hosts:
        - prometheus.byhyeon.com

auth:
  enabled: true
  secretName: prometheus-auth-secret

serviceAccounts:
  server:
    create: true
    name: prometheus

rbac:
  create: true