serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      - job_name: kubernetes-cadvisor
        static_configs:
          - targets:
              - localhost:8080 

image:
  repository: prom/prometheus
  tag: v2.51.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090
  targetPort: 9090

ingress:
  enabled: true
  ingressClassName: traefik
  clusterIssuer: letsencrypt-http
  serviceName: prometheus
  hosts:
    - prometheus.byhyeon.com
  tls:
    - secretName: prometheus-tls
      hosts:
        - prometheus.byhyeon.com

auth:
  enabled: true
  secretName: prometheus-auth-secret
