server:
  global:
    scrape_interval: 10s

  extraScrapeConfigs:
    - job_name: 'kubernetes-cadvisor'
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
        - role: node

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - prometheus.byhyeon.com
  tls:
    - secretName: prometheus-tls
      hosts:
        - prometheus.byhyeon.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"