server:
  global:
    scrape_interval: 10s

image:
  repository: prom/prometheus
  tag: v2.51.0
  pullPolicy: IfNotPresent

  extraScrapeConfigs:
    - job_name: 'kubernetes-cadvisor'
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
        - role: node

service:
  type: ClusterIP
  port: 9090
  targetPort: 9090

ingress:
  enabled: true
  ingressClassName: traefik
  clusterIssuer: letsencrypt-http
  hosts:
    - prometheus.byhyeon.com
  tls:
    - secretName: prometheus-tls
      hosts:
        - prometheus.byhyeon.com
auth:
  enabled: true # basic auth 적용
  secretName: prometheus-auth-secret