services:
  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    restart: always
    networks:
      - shared
    env_file:
      - ./airflow/.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}

    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000


networks:
  shared:
    external: true
