version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: shared-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared

volumes:
  postgres_data:
  
networks:
  shared:
    name: shared