# 하나로 실행해보기 웹서버랑 , 스케쥴러 나눈이유 찾아보기 
#빌드할때 도커파일 찾아가야하는데 , 2개 하나의 도커파일로 실행하는지 확인해보기 
# airflow_dags: /opt/airflow/dags
# /opt/airflow/config
# :rw
#driver bridge elk라는 공간안에 bridge로 연결

services:
  airflow-webserver:
    build:
     context: ./airflow location
    image: voice-clone-airflow:latest
    container_name: airflow-webserver
    # .env : AIRFLOW_UID
    user: "${AIRFLOW_UID}:0"   
    env_file:
      - ./airflow/.env
    
    #postgresql connect
    depends_on:
      - postgres

    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=supersecretkey
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AIRFLOW__WEBSERVER__BASE_URL=https://hyeonjh.duckdns.org/

      #postsql env add 
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      # aws 관련
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-amazon
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

      # entrypoint setting
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
    entrypoint: /opt/airflow/entrypoint.sh  

    command: webserver
    restart: always
    networks:
      - shared  

  airflow-scheduler:
    build:
     context: ./airflow 
    image: voice-clone-airflow:latest
    container_name: airflow-scheduler
    # .env : AIRFLOW_UID
    user: "${AIRFLOW_UID}:0"   
    env_file:
      - ./airflow/.env 

    #postgresql connect
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      #postsql env add 
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      # aws 관련
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-amazon
    volumes:
      - ./airflow/dags:/opt/airflow/dags #:rw 
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      # entrypoint setting
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
    entrypoint: /opt/airflow/entrypoint.sh  

    command: scheduler
    restart: always
    networks:
      - shared    

networks:
  shared:
    external: true