apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-token-refresher
  namespace: kube-system
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ecr-login
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - |
                  aws ecr get-login-password --region {{ .Values.region }} | \
                  kubectl create secret docker-registry ecr-registry \
                  --docker-server={{ .Values.accountId }}.dkr.ecr.{{ .Values.region }}.amazonaws.com \
                  --docker-username=AWS \
                  --docker-password=$(aws ecr get-login-password --region {{ .Values.region }}) \
                  --namespace {{ .Values.namespace }} \
                  --dry-run=client -o yaml | kubectl apply -f -
                  echo "🛡️ Checking ECR repositories..."
                  aws ecr describe-repositories

                  echo "✅ ECR refresh completed!"
              env:
                {{- toYaml .Values.env | nindent 16 }}
          restartPolicy: OnFailure
          serviceAccountName: ecr-access-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: kube-system