{{- if .Values.serverFiles.prometheus }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |-
{{ toYaml .Values.serverFiles.prometheus | indent 4 }}
{{- end }}
