{{- if and .Values.ingress.enabled .Values.auth.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  basicAuth:
    secret: {{ .Values.auth.secretName }}
{{- end }}
