apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: prometheus
