apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9090
  selector:
    app: prometheus
    component: server
