services:
  airflow-webserver:
    build:
     context: ./airflow
    image: byhyeon-airflow:latest
    container_name: airflow-webserver
    # .env : AIRFLOW_UID
    user: "${AIRFLOW_UID}:0"   
    env_file:
      - ./airflow/.env
    
    #postgresql connect
    depends_on:
      - airflow-scheduler # 도커 컨테이너 실행 "순서"를 보장 (필수아님)
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=supersecretkey
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AIRFLOW__WEBSERVER__BASE_URL=${AIRFLOW__WEBSERVER__BASE_URL}
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Seoul

      # airflow db migrate시 메타정보가 바라보는 스키마 변경 
      - AIRFLOW__DATABASE__SQL_ALCHEMY_SCHEMA=airflow_meta

      #postsql env add 
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-amazon
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

      # entrypoint setting
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
    entrypoint: /opt/airflow/entrypoint.sh  

    command: webserver
    restart: always
    networks:
      - shared  

  airflow-scheduler:
    build:
     context: ./airflow 
    image: byhyeon-airflow:latest
    container_name: airflow-scheduler
    # .env : AIRFLOW_UID
    user: "${AIRFLOW_UID}:0"   
    env_file:
      - ./airflow/.env 
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Seoul

      # airflow db migrate시 메타정보가 저장되는 스키마 변경 
      - AIRFLOW__DATABASE__SQL_ALCHEMY_SCHEMA=airflow_meta

      #postsql env add 
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      # aws 관련
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-amazon
    volumes:
      - ./airflow/dags:/opt/airflow/dags #:rw 
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      # entrypoint setting
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
    entrypoint: /opt/airflow/entrypoint.sh  

    command: scheduler
    restart: always
    networks:
      - shared    

networks:
  shared:
    external: true


# test3: 자동 재시작 트리거 테스트