adminPassword: admin

service:
  type: ClusterIP
  port: 80

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

grafana.ini:
  server:
    root_url: https://grafana.byhyeon.com/

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.byhyeon.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.byhyeon.com