adminPassword: admin

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

image:
  repository: grafana/grafana
  tag: 10.3.1
  pullPolicy: IfNotPresent

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

grafana.ini:
  server:
    root_url: https://grafana.byhyeon.com/
  auth.anonymous:
    enabled: true
    org_role: Viewer

ingress:
  enabled: true
  ingressClassName: traefik
  clusterIssuer: letsencrypt-http
  serviceName: grafana
  hosts:
    - grafana.byhyeon.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.byhyeon.com