apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9100
  selector:
    app: node-exporter
  type: {{ .Values.service.type }}
