schedule: "0 */6 * * *"
region: "ap-northeast-2"
accountId: "329599615061"
repository: "byhyeon"
namespace: "fastapi"

image:
  repository: 329599615061.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-token-refresher
  tag: latest
  pullPolicy: Always

env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: byhyeon-secret
        key: AWS_ACCESS_KEY_ID

  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: byhyeon-secret
        key: AWS_SECRET_ACCESS_KEY

  - name: AWS_REGION
    value: ap-northeast-2

rbac: #fastapi 네임스페이스안에 secret 권한부여
  targetNamespace: fastapi