schedule: "0 */6 * * *"
region: "ap-northeast-2"
accountId: "329599615061"
repository: "byhyeon"
namespace: "fastapi"

image:
  repository: 329599615061.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-token-refresher
  tag: latest
  pullPolicy: Always